name: ci

on:
  push:
    branches: 
      - master
      - dev

jobs:

  tests:
    name: Building, testing, and pushing images
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
          
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      run: |-
        cd pipeline1 && docker build -t achippa2112/mgmt590-gcs:${{  github.sha }} .
        docker push achippa2112/mgmt590-gcs:${{  github.sha }} && cd ../
        cd pipeline2 && docker build -t achippa2112/mgmt590-sql:${{  github.sha }} .
        docker push achippa2112/mgmt590-sql:${{  github.sha }}
